### ISSUE TITLE
Mobile menu is bugged

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-web#566] opened 2022-06-30 21:09 UTC
You can't close menu after it opens.

![Screenshot 2022-06-30 at 23 08 45](https://user-images.githubusercontent.com/86911296/176778820-224aa3fc-3783-4ce1-bbe5-1e825bb64e32.png)

**Comment by gpxl-dev** [comment] 2022-06-30 21:41
Dupe of #563

**Closed** 2022-06-30 21:41 UTC
Labels: bug
